### PR TITLE
Adding invert polygon feature

### PR DESCRIPTION
**Pull request by jhnwllr**
Adding an invert polygon button that was requested by a few people in testing. 

image

Only works with simple polygons. Needs warning message or some feedback for MULTIPOLYGONS.

### CODE REVIEW

**Comment by MortenHofft** [comment]
Does it handle polygons crossing the dateline?

**Comment by jhnwllr** [comment]
@MortenHofft pretty sure no.

**Comment by MortenHofft** [comment]
Do you want to add it anyhow? It might fail in those cases I guess then. But that might be okay for a conceptual demo?

**Comment by jhnwllr** [comment]
Yes, it's mostly just for experimental phase to show how it would work in practice. Also I found it to be pretty useful, and I think the new test users will find it useful.

**Pull request merged**
