### PR TITLE
#383 Wrap /grscicoll/institution call in a try-catch to fix crash

### PR DESCRIPTION
**Pull request by jack-brinkman**
See #383

### CODE REVIEW

**Comment by MortenHofft** [comment]
Thanks @jack-brinkman - Are you using this and where?
It was added as an experiment. And in lack of a better API it was done this way. Since then an API to get geojson was added.

**Comment by jack-brinkman** [comment]
No worries @MortenHofft!

I can't see anywhere that we're explicitly using the endpoint (@djtfmartin may know), just that, from our logs, this request weirdly still does get fired. Happy for it to be removed as per #383

**Comment by MortenHofft** [comment]
Ahh, I know why you see it. it just runs in the background and updates continuously. It did that because building the geojson was sooo slow that I had it continously rebuild it every 10 minutes or so. Makes sense. Thanks. It is gone

**Comment by jack-brinkman** [comment]
Ah okay - thanks for removing it :)

**Pull request merged**
